### ISSUE TITLE
how to train multi-class anomaly detection?

### ISSUE THREAD

**Issue by j0987834204** [YoojLee/Uniformaly#1]
First, thanks for your work.
And when I run the multi-category anomaly detection script, I get separate label models. 
How can I modify it so that all categories training on one model?

Many thanks.
Amber

**Comment by YoojLee** [comment]
Hi, thanks for your interest in our work!
I would like to make sure of a few things regarding your question!

1) Did you prepare data for all categories as specified in README? If not, please follow the instructions provided in our README!
2) The provided code prints results per category even though the memory bank was constructed on multiple categories. If you would like to print results for all categories (AUROC for all instances) not in a separate manner, the current code unfortunately does not support that. 

I hope my answer helped you out!

**Comment by j0987834204** [comment]
Thank you for your reply and suggestions.
After checking the reminders in the README as you suggested, I was able to run the code successfully!

Additionally, I would like to clarify about the anomaly clustering results in the paper - are they produced by training a single multi-class classification model? Or are they achieved by first training separate models per anomaly class, and then combining the predictions from these individual models? I would appreciate it if you could shed some light regarding the exact method used for anomaly clustering in the paper.

**Comment by YoojLee** [comment]
Our experiment follows the latter approach. Thanks for your valuable suggestions.  We will clarify our cluster experiment setting in the paper asap!

**Comment by YoojLee** [comment]
This issue will be closed since this thread seems to be completed! If you have further questions or things to discuss, please reopen the issue.
